Repository linkarchive/Front-End, pull requests merged in 2023-08, with the labels that each got.

#214 [FEAT] 팔로우 기능 추가 & 디자인 변경
  __test__/Profile/Profile.test.tsx
  public/assets/svg/alaram-bell.svg
  public/assets/svg/plus.svg
  src/api/API.ts
  src/components/Archive/NicknameModal.tsx
  src/components/Archive/User/Button.tsx
  src/components/Archive/User/Nav.tsx
  src/components/Archive/User/Profile.tsx
  src/components/BottomNav/BottomNav.tsx
  src/components/HashTag/HashTag.tsx
  src/components/HashTag/ReadOnly/HashTag.tsx
  src/components/HashTag/ReadOnly/HashTagList.tsx
  src/components/Header/Header.tsx
  src/components/Input/InputWithButton.tsx
  src/components/Input/index.tsx
  src/components/LinkItem/LinkItem.styled.tsx
  src/components/LinkItem/LinkItem.tsx
  src/components/LinkItem/LinkItemList.tsx
  src/components/LinkItem/LinkItemWithProfile.tsx
  src/components/Settings/FavoriteTagList/index.tsx
  src/components/SvgStyle.styled.tsx
  src/components/ToastBar/index.tsx
  src/components/svg/ChevronDown.tsx
  src/components/svg/PhotoSvgIcon.tsx
  src/components/svg/Svg.tsx
  src/layouts/MainLayout.tsx
  src/layouts/ProfileLayout.tsx
  src/lib/withAuth.ts
  src/pages/[nickname]/index.tsx
  src/pages/_app.tsx
  src/pages/create/index.tsx
  src/pages/index.tsx
  src/pages/settings/index.tsx
  src/pages/settings/profile/index.tsx
  src/pages/settings/trash/index.tsx
  src/store/index.ts
  src/store/slices/routerSlice.ts
  src/styles/GlobalStyle.ts
  src/styles/globals.css
  src/styles/index.ts
  src/styles/palette.ts
  src/styles/theme.ts
Labels: ✨ 개선, ✨ 기능추가

#220 [Feat] 팔로워 조회 페이지
  src/api/API.ts
  src/components/Archive/Follower/Follower.type.ts
  src/components/Archive/Follower/FollowerList.tsx
  src/components/Archive/Follower/Tab.tsx
  src/components/Common/Tab.tsx
  src/hooks/useFollowerTabs.tsx
  src/pages/[nickname]/follower/index.tsx
  src/pages/temp.tsx
  src/store/reducer.ts
  src/store/slices/tabSlice.ts
Labels: ✨ 기능추가

#222 [DESIGN] 프로필 페이지 디자인
  __test__/Settings/Settings.test.tsx
  public/assets/svg/photo.svg
  src/components/Archive/User/Nav.tsx
  src/components/Archive/User/Profile.tsx
  src/components/Archive/User/ProfileImage.tsx
  src/components/BottomNav/BottomNav.tsx
  src/components/BottomNav/CreateBtn.tsx
  src/components/Settings/LinkTo.tsx
  src/components/Settings/ProfileCard.tsx
  src/components/svg/Svg.tsx
  src/layouts/MainLayout.tsx
  src/pages/archive/index.tsx
  src/pages/index.tsx
  src/pages/settings/index.tsx
  src/pages/settings/profile/MessageToaster.tsx
  src/pages/settings/profile/index.tsx
  src/store/slices/routerSlice.ts
  src/styles/palette.ts
Labels: ✨ 개선, 🎨 디자인

#238 [FIX] 기존 pk인 nickname을 userId로 전환
  src/api/API.ts
  src/components/Archive/Follower/FollowerList.tsx
  src/components/Archive/NicknameModal.tsx
  src/components/Archive/User/Button.tsx
  src/components/Archive/User/Profile.tsx
  src/components/Archive/User/User.type.ts
  src/components/HashTag/ReadOnly/HashTag.tsx
  src/components/HashTag/ReadOnly/HashTagList.tsx
  src/components/LinkItem/LinkItemWithProfile.tsx
  src/components/Settings/FavoriteTagList/index.tsx
  src/layouts/ProfileLayout.tsx
  src/lib/withAuth.ts
  src/pages/[nickname]/follower/index.tsx
  src/pages/[nickname]/index.tsx
  src/pages/archive/index.tsx
  src/pages/create/index.tsx
  src/pages/index.tsx
  src/pages/settings/hashtag/index.tsx
  src/pages/settings/index.tsx
  src/queries/index.ts
  src/store/slices/hashTagSlice.ts
  src/store/slices/userSlice.ts
Labels: 🔨 수정, ✨ 개선, ✨ 기능추가

#241 [FEAT] 최초 로그인시 닉네임 받는 페이지 구현
  src/components/Archive/NicknameModal.tsx
  src/components/Settings/MessageToaster.tsx
  src/middleware.ts
  src/pages/archive/index.tsx
  src/pages/settings/profile/index.tsx
  src/pages/settings/profile/nickname/index.tsx
  src/store/slices/routerSlice.ts
  src/styles/palette.ts
Labels: ✨ 기능추가

#245 [Refactor] ProfileImage 디렉토리 변경
  src/components/Archive/User/ProfileImage.tsx
  src/components/Common/User/ProfileImage.tsx
Labels: ♻️ 리팩토링

#246 [HOTFIX] api response 변수 변경
  __test__/Profile/mocks/handlers.js
  __test__/Settings/mocks/handlers.js
  src/components/Archive/Follower/Follower.type.ts
  src/components/Archive/Follower/FollowerList.tsx
  src/components/Archive/User/Profile.tsx
  src/components/Archive/User/User.type.ts
  src/components/LinkItem/LinkItem.tsx
  src/components/LinkItem/LinkItem.type.ts
  src/components/Settings/ProfileCard.tsx
  src/hooks/useImage.ts
  src/hooks/useToggleMark.ts
  src/layouts/LinkItemLayout.tsx
  src/middleware.ts
  src/pages/settings/profile/index.tsx
Labels: 🔨 수정

#244 [FIX] 로그인 페이지 디자인 변경
  __test__/Login/Login.test.tsx
  src/pages/login/index.tsx
Labels: ✨ 기능추가, 🎨 디자인

#253 [Refactor] link item components
  public/assets/svg/link-green.svg
  public/assets/svg/link.svg
  src/components/Create/LinkInfo.tsx
  src/components/LinkItem/Button/DeleteButton.tsx
  src/components/LinkItem/Button/MarkButton.tsx
  src/components/LinkItem/Button/MoreButton.tsx
  src/components/LinkItem/LinkInfo.tsx
  src/components/LinkItem/LinkInfo/index.tsx
  src/components/LinkItem/LinkItem.styled.tsx
  src/components/LinkItem/LinkItem.tsx
  src/components/LinkItem/LinkItem.type.ts
  src/components/LinkItem/LinkItem/LinkItem.styled.tsx
  src/components/LinkItem/LinkItem/index.tsx
  src/components/LinkItem/LinkItemInfo.tsx
  src/components/LinkItem/LinkItemList.tsx
  src/components/LinkItem/LinkItemWithProfile.tsx
  src/components/LinkItem/LinkItemWithProfile/Writer.tsx
  src/components/LinkItem/LinkItemWithProfile/index.tsx
  src/components/LinkItem/MetaData/MetaData.steyled.tsx
  src/components/LinkItem/MetaData/Thumbnail.tsx
  src/components/LinkItem/MetaData/index.ts
  src/components/LinkItem/index.ts
  src/components/svg/Svg.tsx
  src/components/svg/todo
  src/pages/temp.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#260 [FEAT] 내 링크가 없을 때 안내 글자 구현
  src/components/BottomNav/CreateBtn.tsx
  src/components/Home/SpeechBubbles/SpeechBubbles.tsx
  src/components/Home/Suggestion/Suggestion.tsx
  src/components/LinkItem/LinkItemList.tsx
  src/components/svg/Svg.tsx
  src/layouts/LinkItemLayout.tsx
  src/layouts/MainLayout.tsx
  src/middleware.ts
  src/pages/[nickname]/index.tsx
  src/pages/archive/index.tsx
  src/pages/feed/index.tsx
  src/pages/index.tsx
  src/store/index.ts
  src/store/reducer.ts
  src/store/slices/countSlice.ts
  src/store/slices/hashTagSlice.ts
  src/styles/globals.css
Labels: ✨ 기능추가, 🎨 디자인

#264 [FIX] 최초 로그인시 둘러보기 기능 제한
  src/middleware.ts
Labels: 🔨 수정

#266 [FIX] 서비스 배경색 조절을 위한 페이지간 높이 조절
  src/components/BottomNav/BottomLine.tsx
  src/components/Common/Bottom/BottomButton.tsx
  src/components/Common/InfinityScroll.tsx
  src/components/Common/Tag/HashTagList.tsx
  src/components/Home/Suggestion/Suggestion.tsx
  src/layouts/LinkItemLayout.tsx
  src/layouts/MainLayout.tsx
  src/pages/create/index.tsx
  src/pages/index.tsx
  src/pages/settings/profile/index.tsx
  src/pages/settings/profile/nickname/index.tsx
  src/styles/globals.css
Labels: 🔨 수정

#268 [Feat] 링크 추가 기능 추가
  src/components/Common/Tag/AddTag.tsx
  src/components/Create/Label/index.tsx
  src/components/Create/LinkInfo.tsx
  src/components/Create/Tag/HashTag.tsx
  src/components/Create/Tag/HashTagList.tsx
  src/components/Create/TextInput/ErrorMessage.tsx
  src/components/Create/TextInput/TextInputProps.tsx
  src/components/Create/TextInput/index.tsx
  src/components/LinkItem/MetaData/MetaData.steyled.tsx
  src/components/LinkItem/MetaData/Thumbnail.tsx
  src/components/svg/Svg.tsx
  src/pages/create/index.tsx
Labels: ✨ 기능추가

#276 [FIX] 태그 수정시 자주 사용하는 태그에 바로 반영
  src/pages/settings/hashtag/index.tsx
Labels: 🔨 수정

#275 [FIX] 마크/언마크 후 바로 적용
  src/components/LinkItem/LinkItemList.tsx
  src/hooks/useInfinityScroll.ts
  src/layouts/LinkItemLayout.tsx
  src/store/slices/countSlice.ts
Labels: 🔨 수정
