Repository linkarchive/Front-End, pull requests merged in 2023-07, with the labels that each got.

#184 [FIX] 비로그인/로그인 분기처리한 코드 하나로 합치기
  src/api/API.ts
  src/api/customAPI.ts
  src/pages/[nickname]/index.tsx
  src/pages/archive/index.tsx
Labels: ♻️ 리팩토링, ✨ 개선

#190 [TEST] 테스트 코드 셋업 & 로그인 페이지 테스트코드 작성
  .eslintrc.json
  __test__/Login.test.tsx
  __test__/Settings.test.tsx
  jest.config.js
  jest.setup.js
  next.config.js
  package-lock.json
  package.json
  src/mocks/handler.js
  src/mocks/server.js
  src/pages/_app.tsx
  src/store/index.ts
  src/utils/test-utils.tsx
  tsconfig.jest.json
Labels: ✅ 테스트

#196 [TEST] 프로필 페이지 test 코드 수정
  __test__/Profile.test.tsx
  src/api/API.ts
  src/pages/settings/profile/index.tsx
  src/utils/cancelToken.ts
Labels: ♻️ 리팩토링, ✨ 개선, ✅ 테스트

#194 [Feat] 해시태그 관리 페이지
  src/api/API.ts
  src/components/Settings/FavoriteTagList/FavoriteTag.tsx
  src/components/Settings/FavoriteTagList/index.tsx
  src/components/Settings/TagForm/index.tsx
  src/pages/create/index.tsx
  src/pages/settings/hashtag/index.tsx
  src/pages/settings/index.tsx
  src/queries/index.ts
  src/store/slices/routerSlice.ts
  src/utils/validation.ts
Labels: ✨ 기능추가

#198 [HOTFIX] 비동기 방어코드 추가
  src/pages/settings/profile/index.tsx
Labels: 🔨 수정

#199 [FEAT] 링크 아이템 삭제 기능
  src/api/API.ts
  src/components/Common/InfinityScroll.tsx
  src/components/LinkItem/DeleteButton.tsx
  src/components/LinkItem/LinkItemLits.tsx
  src/hooks/useInfinityScroll.ts
  src/pages/[nickname]/index.tsx
  src/pages/archive/index.tsx
  src/pages/index.tsx
  src/pages/settings/index.tsx
  src/pages/settings/trash/index.tsx
  src/store/slices/routerSlice.ts
Labels: ✨ 기능추가

#201 [FEAT] 해시태그 필터링 기능구현
  .husky/pre-commit
  package-lock.json
  public/assets/svg/chevron-down.svg
  public/assets/svg/chevron-up.svg
  src/api/API.ts
  src/components/Archive/ArchiveHeader.tsx
  src/components/Archive/NicknameModal.tsx
  src/components/Archive/User/Nav.tsx
  src/components/Archive/User/Profile.tsx
  src/components/HashTag/ReadOnly/HashTag.tsx
  src/components/HashTag/ReadOnly/HashTagList.tsx
  src/components/Home/HomeHeader.tsx
  src/components/LinkItem/LinkItem.tsx
  src/components/LinkItem/LinkItemList.tsx
  src/components/LinkItem/LinkItemWithProfile.tsx
  src/components/LinkItem/index.ts
  src/components/svg/ChevronDown.tsx
  src/hooks/useAuth.ts
  src/hooks/useImage.ts
  src/hooks/useToggleMark.ts
  src/layouts/LinkItemLayout.tsx
  src/pages/[nickname]/index.tsx
  src/pages/auth/kakao/index.tsx
  src/pages/create/index.tsx
  src/pages/index.tsx
  src/pages/settings/index.tsx
  src/pages/settings/profile/index.tsx
  src/store/index.ts
  src/store/reducer.ts
  src/store/slices/hashTagSlice.ts
  src/store/slices/homeSlice.ts
  src/store/slices/navSlice.ts
  src/store/slices/toastBarSlice.ts
  src/store/slices/userSlice.ts
Labels: ✨ 기능추가
